### ISSUE TITLE
Minimal Workspace Distraction while Visible

### ISSUE THREAD

**Issue by wolz-CODElife** [adenekan41/scoutbar#1]
I will like to contribute a feature we users should have an option to open a minimal pane, it can be:
- Dragged around or repositioned.
- Resizable.

**Comment by adenekan41** [comment]
Hey @wolz-CODElife 

These are amazing features. I appreciate you taking the time to do this. There may be some complications in them, here's why, and how I think we could deal with it holistically.

## Dragged around or repositioned.
Originally this feature was supposed to come out with this current major version, but I had some concerns

With the Scoutbar, it is common for users to typically trigger the bar and search for anything they want, and presto the whole process is complete. Even in a very rare case of the scoutbar needing to be repositioned, clicking outside would automatically close the scoutbar, which means that the probability of someone clicking outside the bar and still keeping it open is a really slim percentage. To balance this, we have a prop called `bodyScroll` (defaults `false`) which disables page scrolling when the bar is opened.

Based on this, I created a spec that would be most useful for this experience.

### Spec for `[Dragged around or repositioned]`
The following is my suggested implementation if we want to go forward with it.

- The Scoutbar component is initiated with a `draggable (boolean)` prop
```jsx
<ScoutBar
    draggable
/>
```
- It is important to note that the Drag method works only in conjunction with the `noResultsInEmptySearch`, that is, you can only drag the scoutbar if these two props are available. Ideally, when the `draggable` prop is true, we activate the `noResultsOnEmptySearch` automatically, so we have a cleaner drag interface and syntax. (How you want this to work is really up to you).

And yeah that’s pretty much it for this feature

## Resizable.
My thoughts on this are pretty foggy not sure I fully understand how this is supposed to work, mind giving a bit of insight into how you think it should work?

By the way, these are pretty impressive features and I can't wait for this to get into Scoutbar. Great work, man 🚀

**Comment by wolz-CODElife** [comment]
## Dragged around or repositioned.
> Even in a very rare case of the scoutbar needing to be repositioned, clicking outside would automatically close the scoutbar, which means that the probability of someone clicking outside the bar and still keeping it open is a really slim percentage. To balance this, we have a prop called bodyScroll (defaults false) which disables page scrolling when the bar is opened.

Considering a workspace like Dropbox Paper, some navigators might still need to be visible while work-in-progress. 

Taking the ` spec for [Dragged around or repositioned] `, if a ` draggable (boolean)  === true `, then the features that automatically closes the bar when clicking outside it and the ` bodyScroll (defaults false) ` can be conditioned.  


## Resizable.
Might be dependent on the ` Drag around or repositioned ` feature, in the sense that... If it is draggable, then there is certainly work-in-progress outside the scoutbar.
A user might not want to close the scoutbar entirely, but will want it less distracting. 
### Spec for ` Resizable `
- The scoutbar will accept a ` resizable ` prop that will only function if ` draggable === true `:
```javascript
<ScoutBar
    draggable
    resizable
/>
```

What do you think?
You're doing well boss 👊

**Comment by adenekan41** [comment]
> Taking the spec for [Dragged around or repositioned], if a draggable (boolean) === true, then the features that automatically closes the bar when clicking outside it and the bodyScroll (defaults false) can be conditioned.

That's good intuition. sounds good to me. 

as for the resizable, I'm a bit skeptical about this for now. can we just go ahead with the draggable for now? 

So far all this looks nice. great job man 🚀

**Comment by wolz-CODElife** [comment]
Alright, we can suspend the **Resizable** idea for now.

So, can I start working on the draggable props and function? Then make a PR when I'm done.

**Comment by adenekan41** [comment]
Correct. 

That said in this PR https://github.com/adenekan41/scoutbar/pull/4 I created a test env for you to work with. 

and also documented how to run it in the readme. let me know if you have any issues with starting it up

**Comment by adenekan41** [comment]
hey @wolz-CODElife how's this task coming along? 

Please don’t hesitate to reach out if you need any of my help 🚀

**Comment by wolz-CODElife** [comment]
hi, I'm currently on a new Windows 10 machine and I've not used yarn on it.
So now I tried setting up yarn, I'm having some little issues😣😥. Once I find my way around these issues, I will proceed with the feature.
Here is a sample of the error:
```shell
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⡀ iltorb
[-/3] ⡀ waiting...
error C:\xampp\htdocs\Learning React\scoutbar\node_modules\iltorb: Command failed.
Exit code: 1
Command: node ./scripts/install.js || node-gyp rebuild
Arguments:
Directory: C:\xampp\htdocs\Learning React\scoutbar\node_modules\iltorb
Output:
info looking for cached prebuild @ C:\Users\user\AppData\Roaming\npm-cache\_prebuilds\ee308d-iltorb-v2.4.5-node-v83-win32-x64.tar.gz
http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-win32-x64.tar.gz
http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-win32-x64.tar.gz
WARN install No prebuilt binaries found (target=14.18.0 runtime=node arch=x64 libc= platform=win32)

C:\xampp\htdocs\Learning React\scoutbar\node_modules\iltorb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.0 | win32 | x64
gyp info find Python using Python version 3.9.2 found at "C:\Users\user\AppData\Local\Programs\Python\Python39\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1745) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\user\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\xampp\htdocs\Learning React\scoutbar\node_modules\iltorb
gyp ERR! node -v v14.18.0
gyp ERR! node-gyp -v v5.1.0
```

If you have any idea how to go around this, I will love to try it.

Thanks🤝

**Comment by adenekan41** [comment]
Sure thing man happy to help. 

This should solve the issues just fine for you, on an admin shell, simply install the build tools package globally [node-gyp README](https://github.com/nodejs/node-gyp#on-windows):

```
npm i -g windows-build-tools
```

See here for the full resolution LOGS https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c 

Let me know if this helps

**Comment by wolz-CODElife** [comment]
Hi, thanks for the guide.
I have followed all the recommended steps so far, but there's no progress.
After running ` npm I -g windows-build-tools `, the shell doesn't go past here:

![image](https://user-images.githubusercontent.com/55518764/143085939-b4674a70-1440-4911-ab8b-568835aa85c0.png)

Thanks for the assistance this far, or will you do giveaway... let me buy Macbook🤲
