### ISSUE TITLE
latest release breaks NextJS app

### ISSUE THREAD

**Issue by danielcherrington** [adenekan41/scoutbar#16]
I have updated to the latest release and it has broken my app.
I havent looked into the issue in detail but it seems to be trying to access the window object when it doesnt exist
```
ReferenceError: window is not defined
    at Object.<anonymous> (\node_modules\scoutbar\dist\bundle-cjs\helpers\use-keyboard-navigation.js:24:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Daniel\dev\flashcrm\node_modules\scoutbar\dist\bundle-cjs\index-5f7b1e16.js:19:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
111

**Comment by adenekan41** [comment]
Thanks for the quick call out fix has been added in this build
[npmjs.com/package/scoutbar/v/1.2.3](https://www.npmjs.com/package/scoutbar/v/1.2.3)
